[package]
name = "aoc2018"
version = "0.1.0"
authors = ["scullionw <scuw1801@usherbrooke.ca>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
regex = "1.1.6"
lazy_static = "1.3.0"
bytecount = "0.5.1"
benchtest = "0.1.1"
